version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  main_job:
    executor:
      name: node/default
      tag: "14.18"
    steps:
      - checkout
      - node/install-packages
      - run: npm test
      - store_test_results
workflows:
  main:
    jobs:
      - main_job
